[package]
name = "todors"
authors = ["Iurii Kondrakov <deezzir@gmail.com>"]
version = "1.0.0"
description = "Interactive TODO application in terminal"
edition = "2021"

[dependencies]
regex = "1.3.9"
chrono = "0.4.23"
ncurses = { version = "5.101.0", features = ["wide"] }
